apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admincluster
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
  namespace: privileges
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
