// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: api/v1/gservice.proto

package api_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GServiceClient is the client API for GService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GServiceClient interface {
	ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*Pods, error)
}

type gServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGServiceClient(cc grpc.ClientConnInterface) GServiceClient {
	return &gServiceClient{cc}
}

func (c *gServiceClient) ListPods(ctx context.Context, in *ListPodsRequest, opts ...grpc.CallOption) (*Pods, error) {
	out := new(Pods)
	err := c.cc.Invoke(ctx, "/api.v1.GService/ListPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GServiceServer is the server API for GService service.
// All implementations must embed UnimplementedGServiceServer
// for forward compatibility
type GServiceServer interface {
	ListPods(context.Context, *ListPodsRequest) (*Pods, error)
	mustEmbedUnimplementedGServiceServer()
}

// UnimplementedGServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGServiceServer struct {
}

func (UnimplementedGServiceServer) ListPods(context.Context, *ListPodsRequest) (*Pods, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPods not implemented")
}
func (UnimplementedGServiceServer) mustEmbedUnimplementedGServiceServer() {}

// UnsafeGServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GServiceServer will
// result in compilation errors.
type UnsafeGServiceServer interface {
	mustEmbedUnimplementedGServiceServer()
}

func RegisterGServiceServer(s grpc.ServiceRegistrar, srv GServiceServer) {
	s.RegisterService(&GService_ServiceDesc, srv)
}

func _GService_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GServiceServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.GService/ListPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GServiceServer).ListPods(ctx, req.(*ListPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GService_ServiceDesc is the grpc.ServiceDesc for GService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.GService",
	HandlerType: (*GServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPods",
			Handler:    _GService_ListPods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/gservice.proto",
}
